name: multiple runners and choose jobs
on:
 workflow_dispatch:
  inputs:
    runner:
      description: "Select the runner"
      required: true
      type: choice
      options:
        - ubuntu-latest
        - ubuntu-22.04
        - self-hosted
        - windows-latest
    jobs-name:
      description: "select the job to run"
      required: true
      type: choice
      options:
        - buildjob
        - testjob
        - deployjob
    
jobs:
  buildjob:
    if: ${{ github.event.inputs.jobs-name == 'buildjob'}}
    runs-on: ${{github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "build the code"
  testjob:
    if: ${{ github.event.inputs.jobs-name == 'testjob'}}
    runs-on: ${{github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "test the code on runner"
  deployjob:
    if: ${{ github.event.inputs.jobs-name == 'deployjob'}}
    runs-on: ${{github.event.inputs.runner}}
    steps:
    - name: deploy code
      run: echo "deploy the code on runner"  

